Repository ikloster03/vue-dadata, pull requests merged in 2019-10, with the labels that each got.

#3 Init project
  .browserslistrc
  .gitignore
  babel.config.js
  cypress.json
  jest.config.js
  package.json
  postcss.config.js
  public/index.html
  src/App.vue
  src/main.ts
  src/shims-tsx.d.ts
  src/shims-vue.d.ts
  tests/e2e/plugins/index.js
  tests/e2e/specs/test.js
  tests/e2e/support/commands.js
  tests/e2e/support/index.js
  tests/unit/example.spec.ts
  tsconfig.json
  tslint.json
  yarn.lock
Labels: enhancement

#4 Add configs
  .editorconfig
  .prettierrc
Labels: enhancement

#9 Feature/issue 8
  .prettierrc
  package.json
  src/App.vue
  src/components/VueDadata.vue
  src/types/DadataAddress.ts
  yarn.lock
Labels: enhancement, good first issue

#10 Feature/issue 7
  src/api/getSuggestions.ts
  src/components/VueDadata.vue
  src/types/DadataAddress.ts
  src/types/DadataSuggestion.ts
  src/types/Suggestion.ts
Labels: enhancement

#12 Feature/issue 11
  src/components/VueDadata.vue
Labels: enhancement

#15 Add word's highlighter
  package.json
  src/components/VueDadata.vue
  yarn.lock
Labels: enhancement

#18 Fix select events
  src/components/VueDadata.vue
Labels: bug

#22 Add style for input and suggestions
  src/components/VueDadata.vue
Labels: feature

#23 Feature issue 21
  package.json
  rollup.config.js
  src/entry.js
  yarn.lock
Labels: feature

#26 Fix rollup
  rollup.config.js
Labels: bug

#27 Feature issue 24
  src/components/VueDadata.vue
Labels: bug, feature

#28 Feature issue 2
  CHANGELOG.md
  README.md
  package.json
Labels: feature

#30 Add error handler
  src/App.vue
  src/api/getSuggestions.ts
  src/components/VueDadata.vue
Labels: feature

#32 Feature issue 31
  rollup.config.js
  src/api/getSuggestions.ts
  src/components/VueDadata.vue
  src/types/Suggestion.ts
Labels: feature

#33 v1.1.0
  package.json
Labels: feature
