Repository ikloster03/vue-dadata, pull requests merged in 2020-06, with the labels that each got.

#45 Issue 44
  .gitignore
  src/App.vue
  yarn.lock
Labels: documentation, question

#48 add location options for request
  README.md
  package.json
  src/App.vue
  src/api/getSuggestions.ts
  src/components/VueDadata.vue
  src/types/DadataAddress.ts
  src/types/LocationOptions.ts
  src/types/Suggestion.ts
Labels: feature

#50 Issue 49
  package.json
  src/components/VueDadata.vue
  yarn.lock
Labels: bug

#55 update changelog
  CHANGELOG.md
Labels: documentation

#58 config: add ci/cd
  .github/workflows/main.yml
  package.json
Labels: feature

#63 Update readme
  CHANGELOG.md
  README.md
  package.json
  ru/README.md
Labels: documentation

#65 Fix ci cd
  .github/workflows/main.yml
  CHANGELOG.md
  package.json
Labels: documentation

#76 `autoSelectOnEnter` property logic
  README.md
  ru/README.md
  src/components/VueDadata.vue
Labels: feature

#77 Fix inChange bug
  package.json
  src/components/VueDadata.vue
Labels: bug
